---
- hosts: web

  tasks:

  - name: Install apache
    yum:
      name: httpd
      state: installed

  - name: Start apache
    service:
      name: httpd
      state: started
      enabled: yes
...